# ZINC Graph Regression configuration

data:
  name: ZINC
  root: ${oc.env:HOME}/.cache/energy-transformer/data
  # ZINC specific settings
  max_num_nodes: 38  # Max nodes in ZINC dataset
  batch_size: 128
  num_workers: 0
  pos_encoding_method: eigen

model:
  input_dim: 1   # ZINC has 1D node features
  out_dim: 1     # Regression task (1 output)
  embed_dim: 256
  num_heads: 8
  qk_dim: 32
  pos_encoding_dim: 8
  num_layers: 1
  mlp_ratio: 4.0
  num_time_steps: 5
  step_size: 1.0
  norm_eps: 1e-6
  attn_bias: false
  mlp_bias: false

train:
  epochs: 500  # ZINC typically needs more epochs
  optimizer:
    lr: 1e-4
    betas: [0.9, 0.999]
    weight_decay: 0.00001
  gradient_clip: 1.0
  scheduler:
    enabled: true
    eta_min: 1e-6

# Misc
seed: 3407
save_interval: 10
checkpoint_dir: checkpoints/${data.name}
result_dir: results/${data.name}
visualization_dir: visualizations/${data.name}

# Hydra configuration
hydra:
  run:
    dir: outputs/${data.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${data.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true