# NCI1 Graph Classification configuration

data:
  name: NCI1
  root: ${oc.env:HOME}/.cache/energy-transformer/data
  # NCI1 specific settings
  max_num_nodes: 111  # Max nodes in NCI1 dataset
  batch_size: 64
  use_node_attr: false  # NCI1 has node labels only
  cleaned: false
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  pos_encoding_method: eigen
  num_workers: 0

model:
  input_dim: 37   # NCI1 has 37 unique node labels
  out_dim: 2      # Binary classification
  embed_dim: 256
  num_heads: 8
  qk_dim: 32
  pos_encoding_dim: 16
  num_layers: 1
  mlp_ratio: 4.0
  num_time_steps: 5
  step_size: 1.0
  norm_eps: 1e-6
  attn_bias: false
  mlp_bias: false
  hopfield_activation_type: tanh  # Use Tanh activation

train:
  epochs: 200
  optimizer:
    lr: 3e-4
    weight_decay: 0.0001
  gradient_clip: 1.0
  scheduler:
    enabled: false

# Misc
seed: 3407
save_interval: 10
checkpoint_dir: checkpoints/${data.name}
result_dir: results/${data.name}
visualization_dir: visualizations/${data.name}

# Hydra configuration
hydra:
  run:
    dir: outputs/${data.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${data.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true